# Generated by Django 5.1.5 on 2025-01-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('VLO', 'VLOS'), ('BVLOS1', 'BVLOS 1km'), ('BVLOS2', 'BVLOS 2km'), ('NIGHT_VLO', 'Night VLOS'), ('NIGHT_BVLOS5', 'Night BVLOS 5km')], max_length=20)),
                ('drone_platform', models.CharField(choices=[('DJI', 'DJI'), ('EBEE', 'Ebee X'), ('UOB_GLIDER', 'UoB Glider'), ('SMURF', 'Papa Smurf'), ('CODRONE', 'CoDrone'), ('PARROT', 'Parrot Anafi')], max_length=20)),
            ],
        ),
    ]
