# Generated by Django 5.1.5 on 2025-01-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WildProcedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='multiple_drones',
            field=models.CharField(choices=[('SINGLE', 'Single drone'), ('MULTIPLE', 'Multiple Drones'), ('SWARM', 'Drone Swarm')], default='SINGLE', max_length=20),
        ),
    ]
