# Generated by Django 5.1.5 on 2025-01-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WildProcedures', '0002_procedure_multiple_drones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='multiple_drones',
            new_name='number_of_drones',
        ),
        migrations.AlterField(
            model_name='procedure',
            name='operation_type',
            field=models.CharField(choices=[('VLOS', 'VLOS'), ('BVLOS_NO_VO', 'BVLOS up to 1km (No Observer)'), ('BVLOS_VO', 'BVLOS up to 2km (Observer)'), ('NIGHT_VLOS', 'Night VLOS'), ('NIGHT_BVLOS', 'Night BVLOS')], max_length=20),
        ),
    ]
