# Generated by Django 4.2.18 on 2025-01-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WildProcedures', '0004_alter_procedure_drone_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='operation_type',
            field=models.CharField(choices=[('VLOS', 'VLOS'), ('BVLOS_NO_VO', 'BVLOS 1km (No Observer)'), ('BVLOS_VO', 'BVLOS 2km (Observer)'), ('NIGHT_VLOS', 'Night VLOS'), ('NIGHT_BVLOS', 'Night BVLOS')], default='VLOS', max_length=20),
        ),
    ]
