# Generated by Django 5.1.3 on 2024-11-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('request_state', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined')], default='requested', max_length=10)),
                ('activation_state', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='deactivated', max_length=12)),
            ],
        ),
    ]
