# Generated by Django 5.1.5 on 2025-01-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='drone_platform',
            field=models.CharField(choices=[('DJI', 'DJI'), ('EBEE', 'Ebee X'), ('UOB_GLIDER', 'UoB Glider'), ('SMURF', 'Papa Smurf'), ('CODRONE', 'CoDrone'), ('PARROT', 'Parrot Anafi')], default='DJI', max_length=20),
        ),
        migrations.AddField(
            model_name='operation',
            name='number_of_drones',
            field=models.CharField(choices=[('SINGLE', 'Single Drone'), ('MULTIPLE', 'Multiple Drones'), ('SWARM', 'Swarm of Drones')], default='SINGLE', max_length=20),
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('VLOS', 'VLOS'), ('BVLOS_NO_VO', 'BVLOS up to 1km (No Observer)'), ('BVLOS_VO', 'BVLOS up to 2km (Observer)'), ('NIGHT_VLOS', 'Night VLOS'), ('NIGHT_BVLOS', 'Night BVLOS')], default='VLOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='operation',
            name='activation_state',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='inactive', max_length=12),
        ),
    ]
