# Generated by Django 5.1.5 on 2025-01-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapApp', '0002_operation_drone_platform_operation_number_of_drones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='pic',
            new_name='username',
        ),
        migrations.AddField(
            model_name='operation',
            name='rpic',
            field=models.CharField(choices=[('pilot1', 'Pilot 1'), ('pilot2', 'Pilot 2'), ('pilot3', 'Pilot 3')], default='guy test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='uas',
            field=models.CharField(choices=[('DJI_001', 'DJI Phantom 4 - 001'), ('DJI_002', 'DJI Phantom 4 - 002'), ('EBEE_001', 'Ebee X - 001')], default='uas test', max_length=100),
            preserve_default=False,
        ),
    ]
